#!/bin/sh

set -e

# FIXME: Clean? distclean?
rm -f dosbox
rm -Rf fsbuild/_build

echo "Downloading mame0242.tar.gz..."
URL="https://github.com/mamedev/mame/archive/mame0242.tar.gz"
SHA256="36d35cf0a1d11e3b8bdabed44222e9910be2fb8954ea3579c2ba02576ed385c1"
python3 fsbuild/download.py "$URL" sha256:$SHA256

echo "Extracting mame0242.tar.gz..."
mkdir -p fsbuild/_build
cd fsbuild/_build
rm -Rf mame-src
# unzip ../_sources/mame0242s.exe
tar xf ../_sources/mame0242.tar.gz
# mkdir mame-src
# cd mame-src
# unzip ../mame.zip
# rm ../mame.zip
mv mame-mame0242 mame-src

echo "Bootstrap done"
